# OpenBB Platform + interactive CLI / Terminal, containerized.
# Pinned to the locally-built versions: openbb 4.7.2, openbb-cli 1.4.2.
#
# Built for linux/amd64 on purpose: openbb-cli hard-depends on `pywry` (a Rust
# webview backend) which publishes a prebuilt manylinux x86_64 wheel but NO
# arm64 wheel. Targeting amd64 lets pip install pywry from that wheel instead of
# compiling Rust. On Apple Silicon this image runs under emulation (fine for the
# Terminal's I/O-bound workloads).
FROM --platform=linux/amd64 python:3.12-slim

# OpenBB + CLI versions. Defaults track the last known-good release; the
# update-openbb-docker skill overrides them with --build-arg to match the
# source venv (i.e. origin/main, provided that version is published on PyPI).
ARG OPENBB_VERSION=4.7.2
ARG CLI_VERSION=1.4.2

ENV PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    OPENBB_HOME=/root/.openbb_platform \
    PYKX_IGNORE_QHOME=1 \
    PYKX_UNLICENSED=true \
    # Applied to EVERY pip install below, incl. the extensions, so nothing
    # upgrades a shared lib (pandas/protobuf/fastapi/uvicorn) past what the
    # native extensions tolerate. See extension-constraints.txt.
    PIP_CONSTRAINT=/tmp/extension-constraints.txt

# Extension-first version ceilings (generated by derive-constraints.py). COPY'd
# before any install so PIP_CONSTRAINT can enforce it globally.
COPY extension-constraints.txt /tmp/extension-constraints.txt

# Runtime libraries pywry links against (so `import pywry` succeeds). apt pulls
# the rest of the GTK/WebKit stack as dependencies automatically.
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        ca-certificates curl libwebkit2gtk-4.1-0 libgtk-3-0 \
    && rm -rf /var/lib/apt/lists/*

RUN python -m pip install --upgrade pip setuptools wheel

# OpenBB Platform + interactive CLI / Terminal + analysis extensions.
# NOTE: the `[all]` extra is intentionally NOT used; it pulls openbb-charting,
# whose GUI charts cannot render in a headless container. Everything else is
# installed explicitly.
# The shared-lib ceilings (protobuf<7, pandas<3, fastapi/uvicorn) are NOT pinned
# here anymore — PIP_CONSTRAINT=/tmp/extension-constraints.txt enforces them for
# this and every later install, so a bumped OPENBB_VERSION can't drag a shared
# lib past what the arcticdb/pykx/eodhd extensions tolerate.
RUN pip install \
        "openbb==${OPENBB_VERSION}" \
        "openbb-cli==${CLI_VERSION}" \
        "openbb-technical==1.6.2" \
        "openbb-quantitative==1.6.2" \
        "openbb-econometrics==1.7.2"

# Patch openbb_cftc.cftc_router.build_choices: upstream assumes name/code/
# subcategory are non-None and calls .strip() unconditionally. Some CFTC
# contracts have a NULL subcategory, which crashes the REST server at startup
# (the function is registered as a FastAPI startup event handler) and exits the
# whole API. Guard each access with (... or "").strip().
RUN python - <<'PY'
import re, pathlib
p = pathlib.Path("/usr/local/lib/python3.12/site-packages/openbb_cftc/cftc_router.py")
src = p.read_text()
for attr in ("name", "code", "subcategory"):
    src = re.sub(rf"d\.{attr}\.strip\(\)", f"(d.{attr} or '').strip()", src)
p.write_text(src)
PY
RUN python -c "import ast; ast.parse(open('/usr/local/lib/python3.12/site-packages/openbb_cftc/cftc_router.py').read()); print('cftc_router patch parses OK')"

# Patch openbb_core.api.rest_api CORS setup to allow Chrome's Private Network
# Access preflight. OpenBB Workspace runs at https://pro.openbb.co (a public
# origin); a fetch from there to http://127.0.0.1:6900 is a public->private
# request, which Chrome gates behind an OPTIONS preflight carrying
# Access-Control-Request-Private-Network: true. Starlette's CORSMiddleware
# rejects that with "400 Disallowed CORS private-network" unless
# allow_private_network=True, so the browser never issues the real request and
# the Workspace "Connect backend" test times out. OpenBB passes only
# origins/methods/headers through, with no setting for this.
RUN python - <<'PY'
import pathlib
p = pathlib.Path("/usr/local/lib/python3.12/site-packages/openbb_core/api/rest_api.py")
src = p.read_text()
anchor = "    allow_headers=system.api_settings.cors.allow_headers,\n)"
assert anchor in src, "rest_api.py CORS block not found - upstream changed"
p.write_text(src.replace(anchor, anchor.replace("\n)", "\n    allow_private_network=True,\n)"), 1))
PY
RUN python -c "import ast; ast.parse(open('/usr/local/lib/python3.12/site-packages/openbb_core/api/rest_api.py').read()); print('rest_api CORS patch parses OK')"

# Custom Alpaca provider extension (equity historical pricing via IEX/SIP).
COPY openbb-alpaca/ /opt/openbb-alpaca/
RUN pip install /opt/openbb-alpaca

# Custom ArcticDB integration: provider (read) + OBBject accessor (write).
# Pulls in the arcticdb SDK (which pins pandas<3).
COPY openbb-arcticdb/ /opt/openbb-arcticdb/
RUN pip install /opt/openbb-arcticdb

# Custom kdb+ integration: provider + OBBject accessor + store (PyKX over IPC).
COPY openbb-kdb/ /opt/openbb-kdb/
RUN pip install /opt/openbb-kdb

# Custom EODHD provider extension (equity/ETF historical: EOD + intraday).
COPY openbb-eodhd/ /opt/openbb-eodhd/
RUN pip install /opt/openbb-eodhd

# Custom DuckDB + Polars analytics integration: `.duckdb` OBBject accessor +
# generic store (SQL over results/Parquet, catalog tables). Pulls duckdb/polars/
# pyarrow (pure wheels, no shared-lib pin conflict). No OHLCV provider — stored
# bars are served by provider="arcticdb"; DuckDB queries across them.
COPY openbb-duckdb/ /opt/openbb-duckdb/
RUN pip install /opt/openbb-duckdb

# Custom FMP BULK helpers (whole-market ratios/metrics/statements the standard
# openbb-fmp provider does not expose). Plain library, not a provider.
COPY openbb-fmp-bulk/ /opt/openbb-fmp-bulk/
RUN pip install /opt/openbb-fmp-bulk

# Official OpenBB MCP server: wraps the Platform FastAPI app in-process and
# serves MCP over streamable-http. 1.4.1 requires openbb-core>=1.6.10,<2 and
# fastmcp>=3.2.0 — an exact match for openbb 4.7.2. PIP_CONSTRAINT (the
# extension-first ceilings) still applies to this install, so it cannot drag
# shared libs past what arcticdb/pykx/eodhd tolerate. Launched by the NAS
# compose as: openbb-mcp --host 127.0.0.1 --port 6901 (default transport is
# streamable-http; default port 8001 is NOT used to avoid ambiguity with the
# Spark's gemma port). Endpoint path: /mcp/.
RUN pip install "openbb-mcp-server==1.4.1"
RUN python -c "import openbb_mcp_server; print('openbb-mcp-server import OK')"

# Pre-compile the static package + assets so the first run is instant, and verify
# the platform, CLI, and the custom extensions register at build time. (ruff is
# present in the image, so the static codegen's lint/import-fix step runs.)
RUN python -c "import openbb; openbb.build(); from openbb import obb; \
from openbb_core.app.model.obbject import OBBject; import pywry, openbb_cli; \
assert 'alpaca' in obb.coverage.providers, 'alpaca provider not registered'; \
assert 'arcticdb' in obb.coverage.providers, 'arcticdb provider not registered'; \
assert hasattr(OBBject, 'arcticdb'), 'arcticdb accessor not registered'; \
assert 'kdb' in obb.coverage.providers, 'kdb provider not registered'; \
assert hasattr(OBBject, 'kdb'), 'kdb accessor not registered'; \
assert 'eodhd' in obb.coverage.providers, 'eodhd provider not registered'; \
assert hasattr(OBBject, 'duckdb'), 'duckdb accessor not registered'; \
import openbb_duckdb, openbb_fmp_bulk; \
import duckdb, polars, pyarrow; \
print('OpenBB + CLI + alpaca + arcticdb + kdb + eodhd + duckdb + fmp-bulk OK')"

WORKDIR /workspace

# Self-provision the persistent mount points so the image is drop-in on any host
# (QNAP Container Station, plain Docker) with bind mounts to not-yet-created
# /share/Container/openbb/... paths. Runs as root, so no privilege drop -- just
# `mkdir -p`. OPENBB_HOME persists settings/credentials; /workspace holds user data.
ENV APP_DIRS="/root/.openbb_platform /workspace"
COPY docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
RUN chmod +x /usr/local/bin/docker-entrypoint.sh
ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]

# Default to the interactive Terminal. Override with e.g.:
#   docker run -it openbb-local python      -> Python REPL with `from openbb import obb`
#   docker run -it openbb-local openbb-api  -> REST API server
CMD ["openbb"]
